### ISSUE TITLE
nmap not found

### ISSUE THREAD

**Issue by pablopunk** [mtnalonso/local-pies#1]
After install python-nmap I get this error running `local-pies.py`

```bash
nmap.nmap.PortScannerError: 'nmap program was not found in path.
```

So I had to install `nmap` with `brew install nmap`.

Now it does run but it doesn't find any pie, and I get this error:

```bash
△ ~/repos/local-pies at master• ./local_pies.py 

Selected network: 192.168.1.1/24
[+] Scanning network...
[+] Done.

Traceback (most recent call last):
  File "./local_pies.py", line 92, in <module>
    connect_with_single_device(addresses)
  File "./local_pies.py", line 54, in connect_with_single_device
    ip = next(iter(addresses))
StopIteration
```

**Comment by mtnalonso** [comment]
@pablopunk The requirements are updated and the bug solved. Thank you for your collabotarion!
